# Generated by Django 4.2.8 on 2024-05-12 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('interest', models.IntegerField()),
                ('impressions', models.IntegerField()),
                ('clicks', models.IntegerField()),
                ('spent', models.FloatField()),
                ('total_conversion', models.IntegerField()),
                ('approved_conversion', models.IntegerField()),
                ('fb_campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.fbcampaign')),
            ],
        ),
    ]
